<?php echo $this->imgPage; ?>
<h1>FrontEnd/Login/indexAction</h1>
<div class="container">
    <div class="row">
        <div class="main">
            <h3>Please Log In, or <a href="/join">Sign Up</a></h3>
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <a class="btn btn-block btn-social btn-facebook"><span class="fa fa-facebook"></span>Facebook</a>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <a class="btn btn-block btn-social btn-google"><span class="fa fa-google"></span>Google+</a>
                </div>
            </div>
            <div class="login-or">
                <hr class="hr-or">
                <span class="span-or">or</span>
            </div>
            <form role="form" method="post">
                <div class="form-group">
                    <label for="inputUsernameEmail">Username or
                        email</label>
                    <input type="text" class="form-control" id="username">
                </div>
                <div class="form-group">
                    <a class="pull-right" href="#">Forgot password?</a>
                    <label for="password">Password</label>
                    <input type="password" class="form-control"
                           id="password">
                </div>
                <div class="checkbox pull-right">
                    <label>
                        <input type="checkbox">
                        Remember me </label>
                </div>
                <button type="submit" class="btn btn btn-success">
                    Log In
                </button>
            </form>
        </div>
    </div>
</div>

